[default]
debug = true
api_prefix = '/api'

timezone = 'Asia/Seoul'

user_key_field = 'email'

    [default.base_url]
    api = 'http://seed-dev.hawl.kim:8080/api'
    web = 'http://seed-dev.hawl.kim:8080'

    [default.cors]
    allowed_origins = ['*']
    allow_credentials = true
    allow_methods = ['*']
    allow_headers = ['*']

    [default.role]
    permissions = ['']
    roles = ['']

    [default.jwt]
    algorithm = 'HS256'
    access_token_expires = '30m'
    refresh_token_expires = '7d'
    refresh_token_renewal_before_expire = '1d'  # Renewal refresh token before expiration

        [default.jwt.cookie]
        httponly = true
        domains = []
        
        [default.jwt.cookie.key]
        access = 'access_token'
        refresh = 'refresh_token'

    [default.oauth]
    providers = ['kakao']

        [default.oauth.kakao]
        redirect_uri = '/oauth/kakao'
        handler = 'seed.oauth.kakao.KakaoOAuthHandler'

        api_url = 'https://kapi.kakao.com'
        auth_api_url = 'https://kauth.kakao.com'

    [default.integrate]
        [default.integrate.sentry]
        enable = false
        dsn = ''

            [default.integrate.sentry.options]

        [default.integrate.logstash]
        enable = false
        host = '127.0.0.1'
        port = 5959
        database_path = 'logstash.db'

            [default.integrate.logstash.options]
            transport = 'logstash_async.transport.TcpTransport'
            ssl_enable = false
            ssl_verify = true
            keyfile = ''
            certfile = ''
            ca_certs = ''
            encoding = 'utf-8'

    [default.logging]
    intercept_loggers = [
        'uvicorn',
        'uvicorn.access',
        'uvicorn.error',
        'fastapi'
    ]
    format = '<lk>[{time:YYYY-MM-DD HH:mm:ss.SSS}][{name}:{line}]{extra[headers]} › </lk><level>{level.icon} <underline>{level.name}</underline></level>  {message}'

    [default.database]
    dbms = 'sqlite'
    host = ''
    user = ''
    database = 'seed.db'
    charset = 'utf8'

    [default.redis]
    host = '127.0.0.1'
    port = 6379
    encoding = 'utf-8'

    [default.sqlalchemy]
    commit_on_exit = true

        [default.sqlalchemy.session_args]
        expire_on_commit = false
        autoflush = false

        [default.sqlalchemy.engine_args]
            [default.sqlalchemy.engine_args.connect_args]
            check_same_thread = false
