[default]
debug = true
api_prefix = ''
allowed_origins = []

timezone = 'Asia/Seoul'

    [default.plugin]
        [default.plugin.role]
        permissions = ['auth']
        roles = ['']

        [default.plugin.jwt]
        algorithm = 'HS256'
        access_token_expires = 10800 # seconds
        refresh_token_expires = 86400 # seconds

    [default.logging]
    intercept_loggers = [
        'uvicorn',
        'uvicorn.access',
        'uvicorn.error',
        'fastapi'
    ]

    [default.database]
    dbms = 'sqlite'
    host = ''
    user = ''
    password = ''
    database = 'seed.db'
    charset = 'utf8'

    [default.password]
    database_password = ''

    [default.sqlalchemy]
    commit_on_exit = true

        [default.sqlalchemy.session_args]
        expire_on_commit = false
        autoflush = false

[development]

[production]
debug = false
