[default]
debug = true
api_prefix = ''
allowed_origins = []

    [default.logging]
    intercept_loggers = [
        'uvicorn',
        'uvicorn.access',
        'uvicorn.error',
        'fastapi'
    ]

    [default.database]
    dbms = 'sqlite'
    host = ''
    user = ''
    password = ''
    database = 'seed.db'
    charset = 'utf8'

    [default.password]
    database_password = ''

    [default.sqlalchemy]
    commit_on_exit = true

        [default.sqlalchemy.session_args]
        expire_on_commit = false
        autoflush = false

[development]

[production]
debug = false
