"""init

Revision ID: e9e258a4d867
Revises: 
Create Date: 2021-01-11 16:48:41.191097+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e258a4d867'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_login_histories', 'users', ['user_id'], ['id'])
    op.drop_column('user_login_histories', 'browser')
    op.create_index('user_id', 'user_meta', [], unique=False)
    op.create_index('user_id', 'user_profiles', [], unique=False)
    op.create_index('user_id', 'user_social_accounts', [], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id', table_name='user_social_accounts')
    op.drop_index('user_id', table_name='user_profiles')
    op.drop_index('user_id', table_name='user_meta')
    op.add_column('user_login_histories', sa.Column('browser', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'user_login_histories', type_='foreignkey')
    # ### end Alembic commands ###
