[testing.api_key]
kakao_api_key = 'kakao_api_key'

[testing.secret_key]
jwt_secret_key = 'jwt_secret_key'
aes_secret_key = 'aes_secret_key'

[testing.password]
database_password = 'database_password'
