name: Coverage

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.extract_branch.outputs.branch }}
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install Python dependencies
      uses: BSFishy/pip-action@v1
      with:
        packages: |
          arrow
          dynaconf
          fastapi
          fastapi_sqlalchemy
          flake8
          loguru
          orjson
          pycryptodome
          pydantic
          pydantic_sqlalchemy
          PyJWT
          pytest
          pytest-asyncio
          pytest-cov
          pytest-flake8
          python-logstash-async
          redis
          requests
          SQLAlchemy
          user-agents
          uuid
          uvicorn
    - name: Run Tests And Generate coverage report
      working-directory: ./
      run: |
        ENV=testing pytest --flake8 --cov-report=xml --cov=seed tests/
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage.xml
        flags: unittests
