name: Coverage

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.extract_branch.outputs.branch }}
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Cache pip
      id: cache-venv
      uses: actions/cache@v2
      with:
        path: ./.venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-
          ${{ runner.os }}-
    - name: Install Dependencies
      run: |
        python -m venv ./.venv && . ./.venv/bin/activate && pip install -r requirements.txt
      if: steps.cache-venv.outputs.cache-hit != 'true'
    - name: Run Tests And Generate coverage report
      run: |
        ./.venv/bin/activate && pytest --flake8 --cov-report=xml --cov=seed tests/
      env:
        ENV: testing
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage.xml
        flags: unittests
