name: Unittest

on:
  push:
      branches: [ main, develop ]

jobs:
  run:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: seed_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
  
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.extract_branch.outputs.branch }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.9'
    - name: Start MySQL
      run: |
        sudo apt-get install -y mysql-client libmysqlclient-dev
        mysql --host 127.0.0.1 --port 3306 -uroot -e "SHOW GRANTS FOR 'root'@'localhost'"
    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: 4
    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: requirements.txt
    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
    - run: pip install -r requirements.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
    - name: Create Table into Database with alembic
      run: |
        alembic upgrade head
      env:
        ENV: testing
    - name: Add dummy data on Database
      run: |
        mysql --ho  st 127.0.0.1 --port 3306 -uroot seed_test < tests/testdata.sql
    - name: Run Tests And Generate coverage report
      run: |
        pytest --cov-report=xml
      env:
        ENV: testing
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage.xml
        flags: unittests
